[package]

name = "time_calc"
description = "A library for music/DSP time conversions! Provides functions and methods for converting between ticks, ms, samples, bars, beats and measures."
version = "0.9.3"
authors = ["mitchell.nordine@gmail.com"]
readme = "README.md"
keywords = ["time", "dsp", "audio", "music", "conversion"]
license = "Apache-2.0/MIT"
